-- create table + simple seed + offene Lese-Policy
create table if not exists public.test_table (
  id bigint generated by default as identity primary key,
  note text not null,
  created_at timestamptz not null default now()
);

insert into public.test_table (note)
values ('hello from test_table')
on conflict do nothing;

-- RLS: erlauben (lesen für alle)
alter table public.test_table enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
      where schemaname = 'public'
        and tablename  = 'test_table'
        and policyname = 'read_all'
  ) then
    create policy read_all
      on public.test_table
      for select
      using (true);
  end if;
end$$;
