-- idempotenter Fix für public.test_table
create table if not exists public.test_table (
  id bigint generated by default as identity primary key
);

-- fehlende Spalten ergänzen
alter table public.test_table
  add column if not exists name text not null default 'seed',
  add column if not exists label text,
  add column if not exists created_at timestamptz default now();

-- Seed-Datensatz robust einfügen (mit/ohne name-Spalte)
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='test_table' and column_name='name'
  ) then
    insert into public.test_table (name, label)
    select 'seed', 'hello from migration'
    where not exists (select 1 from public.test_table where label = 'hello from migration');
  else
    insert into public.test_table (label)
    select 'hello from migration'
    where not exists (select 1 from public.test_table where label = 'hello from migration');
  end if;
end$$;