name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch from main
        run: |
          git checkout -b auto-pr-${{ github.run_id }}
          git commit --allow-empty -m "Automated PR commit"
          git push origin auto-pr-${{ github.run_id }}

      - name: Create Pull Request via CLI
        run: |
          gh pr create \
            --base main \
            --head auto-pr-${{ github.run_id }} \
            --title "Automated Pull Request" \
            --body "This PR was automatically created using GitHub CLI and PAT."