name: Auto Merge PRs

on:
  pull_request_target:
    types: [opened, reopened, labeled, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  statuses: read

jobs:
  enable-auto-merge:
    # nur für PRs gegen main und mit dem Label 'auto-merge'
    if: >
      github.event.pull_request.base.ref == 'main' &&
      (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-merge') ||
        contains(join(github.event.pull_request.labels.*.name, ','), 'auto-merge')
      )
    runs-on: ubuntu-latest
    steps:
      # Optional: automatisch approven (falls Approval nötig wäre)
      - name: Auto-approve
        uses: peter-evans/auto-approve@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Built-in Auto-Merge aktivieren (Merge-Methode: squash)
      - name: Enable built-in Auto-Merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
