name: Auto Merge / auto-approve-and-merge

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled]

permissions:
  pull-requests: write
  contents: read

jobs:
  enable-automerge:
    name: Enable built-in Auto-Merge (squash)
    runs-on: ubuntu-latest

    steps:
      - name: Inspect labels (debug/log)
        run: echo "Labels: ${{ toJson(github.event.pull_request.labels.*.name) }}"

      # Falls das Label vorhanden ist -> Auto-Merge einschalten
      - name: Enable Auto-Merge (squash) when label is present
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'auto-merge')
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      # Falls kein Label vorhanden ist -> Job trotzdem erfolgreich beenden
      - name: No auto-merge label — mark job successful
        if: "!contains(join(github.event.pull_request.labels.*.name, ','), 'auto-merge')"
        run: echo "No 'auto-merge' label; finishing job successfully."
