name: auto-merge

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: contains(toJson(github.event.pull_request.labels.*.name), 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable GitHub Auto-Merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash