name: 🤖 Auto‑Fix Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  auto‑fix:
    runs‑on: ubuntu‑latest

    steps:
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_FIX_TOKEN }}

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗 Build Project
        run: npm run build

      - name: 🛠️ Run ESLint Auto‑Fix
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix || true

      - name: ⚙️ Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 💾 Commit Fixes (nur Code-Dateien)
        run: |
          git add .
          git reset .github/workflows/*.yml || true
          git diff --cached --quiet || git commit -m "🤖 Auto‑Fix: Fehler automatisch behoben"

      - name: 🚀 Push Fixes
        env:
          TOKEN: ${{ secrets.AUTO_FIX_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Shanabananarama/mein-tailwind-projekt.git
          git pull --rebase origin main
          git push origin HEAD:main