name: Auto Approve

on:
  pull_request_target:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve pull requests
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}
