name: Auto Merge Pull Requests

on:
  pull_request:
    types: [labeled, opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge PR when ready
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "rebase"
          MERGE_LABELS: "automerge"
          UPDATE_LABELS: "automerge"
          MERGE_REQUIRED_APPROVALS: 0