name: Auto Pull Request Workflow

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_FIX_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Branch
        run: |
          BRANCH_NAME="auto-pr-$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$BRANCH_NAME"
          git push https://x-access-token:${{ secrets.AUTO_FIX_TOKEN }}@github.com/${{ github.repository }} "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.AUTO_FIX_TOKEN }}
          commit-message: "Auto PR Workflow: Änderungen automatisch erstellt"
          title: "Auto PR Workflow Änderungen"
          body: "Dieser Pull Request wurde automatisch vom Auto-PR Workflow erstellt."
          branch: ${{ github.ref }}