name: auto-merge

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, reopened, ready_for_review]

jobs:
  enable_auto_merge:
    if: github.event.action == 'labeled' && github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable PR automerge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

  disable_auto_merge:
    if: github.event.action == 'unlabeled' && github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Disable PR automerge
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo "${{ github.repository }}" \
            --disable-auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}Ï€