name: Auto-Approve & Auto-Merge PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  statuses: read
  checks: read

jobs:
  approve-and-enable-automerge:
    if: >
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.draft == false &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve
        uses: peter-evans/approve@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          message: "Auto-approval for auto-merge."

      # Wartet schrittweise, bis GitHub den PR als 'mergeable' akzeptiert
      # und schaltet dann Auto-Merge (SQUASH) ein.
      - name: Enable Auto-Merge (squash) when ready (with retry)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NODE_ID: ${{ github.event.pull_request.node_id }}
        run: |
          echo "Versuche Auto-Merge zu aktivieren, sobald der PR bereit ist..."
          for i in {1..60}; do
            RES=$(curl -s -H "Authorization: bearer $GH_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST https://api.github.com/graphql \
              -d "{\"query\":\"mutation { enablePullRequestAutoMerge(input: {pullRequestId: \\\"$PR_NODE_ID\\\", mergeMethod: SQUASH}) { clientMutationId }}\"}")
            if echo "$RES" | grep -q "\"errors\""; then
              if echo "$RES" | grep -q "unstable status\\|is in an unstable status\\|not mergeable"; then
                echo "PR noch nicht mergebar (Checks/Reviews?). Warte 20s und versuche erneut..."
                sleep 20
              else
                echo "Unerwarteter Fehler beim Aktivieren von Auto-Merge:"
                echo "$RES"
                exit 1
              fi
            else
              echo "Auto-Merge erfolgreich aktiviert ✅"
              exit 0
            fi
          done
          echo "Timeout: PR wurde nicht rechtzeitig mergebar. Bitte prüfen."
          exit 1
