name: DISABLED - Auto Merge by Label

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Auto-merge per Label ist deaktiviert. Nur manuelles Merge durch dich."
