name: 🤖 Auto-Fix Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: 📂 Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_FIX_TOKEN }}

      # 2️⃣ Node.js einrichten
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Abhängigkeiten installieren
      - name: 📦 Install Dependencies
        run: npm install

      # 4️⃣ Projekt builden
      - name: 🏗 Build Project
        run: npm run build

      # 5️⃣ Linting & automatische Fehlerbehebung
      - name: 🛠️ Run ESLint Auto-Fix
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --fix || true

      # 6️⃣ Git Config einrichten
      - name: ⚙️ Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 7️⃣ Neue Branch für Fix erstellen
      - name: 🌱 Create Fix Branch
        run: |
          BRANCH="auto-fix-$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$BRANCH"
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      # 8️⃣ Änderungen committen (nur Code-Dateien)
      - name: 💾 Commit Fixes
        run: |
          git add .
          git reset .github/workflows/*.yml || true
          git diff --cached --quiet || git commit -m "🤖 Auto-Fix: Fehler automatisch behoben"

      # 9️⃣ Änderungen pushen
      - name: 🚀 Push Fix Branch
        env:
          TOKEN: ${{ secrets.AUTO_FIX_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Shanabananarama/mein-tailwind-projekt.git
          git push origin HEAD:$BRANCH_NAME

      # 🔟 Automatisch Pull Request erstellen
      - name: 🔀 Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.AUTO_FIX_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "🤖 Auto-Fix: Fehler automatisch behoben"
          body: "Dieser PR wurde automatisch erstellt, um gefundene Fehler zu beheben."
          base: main