name: Auto Pull Request

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: main
          # branches unique by timestamp avoids reuse/conflict
          branch: auto-pr-${{ github.run_id }}
          title: Auto Pull Request
          body: |
            This PR was automatically created using workflow_dispatch.
          delete-branch: true