name: 🤖 Auto-Fix bei Fehlern

on:
  push:
    branches:
      - main

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository-Code abrufen
      - name: 📂 Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Node.js installieren
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Abhängigkeiten installieren
      - name: 📦 Install Dependencies
        run: npm install

      # 4️⃣ Auto-Fix ausführen (Lint + Prettier)
      - name: 🔧 Run Auto-Fix
        run: |
          npx eslint . --fix || true
          npx prettier --write . || true

      # 5️⃣ Änderungen committen (nur wenn es Änderungen gab)
      - name: 💾 Commit Fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && echo "✅ Keine Änderungen zum Commit." || git commit -m "🤖 Auto-Fix: ESLint/Prettier Fehler korrigiert"

      # 6️⃣ Änderungen zurück pushen
      - name: 🚀 Push Fixes
        if: success()
        run: git push origin main