name: Auto Approve and Merge PRs

on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review, labeled, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve:
    # Nur PRs gegen main + Label 'auto-merge'
    if: >
      github.event.pull_request.base.ref == 'main' &&
      (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-merge') ||
        contains(join(github.event.pull_request.labels.*.name, ','), 'auto-merge')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # explizit übergeben, damit keine 0 entsteht
          pull-request-number: ${{ github.event.pull_request.number }}

  auto-merge:
    needs: auto-approve
    # gleiche Bedingung wie oben
    if: >
      github.event.pull_request.base.ref == 'main' &&
      (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-merge') ||
        contains(join(github.event.pull_request.labels.*.name, ','), 'auto-merge')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
