name: Auto Pull Request Workflow

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit and push
        run: |
          BRANCH_NAME="auto-pr-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          git commit --allow-empty -m "Automated PR commit"
          git push origin $BRANCH_NAME

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request via CLI
        run: |
          BRANCH_NAME="auto-pr-${{ github.run_id }}"
          gh pr create \
            --base main \
            --head $BRANCH_NAME \
            --title "Automated Pull Request" \
            --body "This PR was automatically created using GitHub CLI and PAT."