name: Fixed AutoPR workflow with Personal Access Token

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create New Branch
        run: |
          BRANCH_NAME=auto-pr-$(date +%Y%m%d%H%M%S)
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "Auto PR Commit"
          branch: ${{ github.head_ref || 'auto-pr-branch' }}
          title: "Auto PR - Code Update"
          body: "Automatisierter Pull Request Workflow"