name: Auto Merge by Label

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: contains(toJson(github.event.pull_request.labels), 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Merge now (fallback)
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request: ${{ github.event.pull_request.number }}
          method: squash
