name: Auto Approve & Prepare Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  approve-and-prepare:
    runs-on: ubuntu-latest
    if: github.actor == 'Shanabananarama' # nur du selbst
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Approve Pull Request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment to indicate ready for merge
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "Auto-Approve"
          message: |
            ✅ Alle Checks erfolgreich. 
            Warte auf manuelle Freigabe von @Shanabananarama zum Merge.
