name: Fixed AutoPR workflow with Personal Access Token

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Branch
        run: |
          BRANCH_NAME="auto-pr-$(date +%Y%m%d%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b "$BRANCH_NAME"
          echo "Automated change $(date)" >> auto-pr-log.txt
          git add auto-pr-log.txt
          git commit -m "Automated commit from workflow"
          git push "https://x-access-token:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}" "$BRANCH_NAME"
        env:
          GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "Automated Pull Request"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Automated Pull Request"
          body: "This is an auto-generated PR using PAT."