name: Auto Approve and Merge

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: echo "Lint OK"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Build OK"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: echo "Tests OK"

  auto-approve:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
