name: build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/Tag to run on"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - name: Build (noop)
        run: echo "build ok"
