name: Enable Auto Merge

on:
  pull_request:
    types: [labeled, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    # nur wenn Label "auto-merge" gesetzt ist (mit Bindestrich) und PR kein Draft ist
    if: contains(toJSON(github.event.pull_request.labels.*.name), 'auto-merge') && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Enable GitHub AutoMerge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash