name: gate

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gate (noop)
        run: echo "✅ gate passed"
