name: Satisfy legacy required checks (manual)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull request number (e.g. 14)"
        required: true
        type: number

jobs:
  satisfy:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: read
    steps:
      - name: Get PR data
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number(core.getInput('pr_number'))
            });
            core.setOutput('sha', pr.data.head.sha);

      # ---- markiere alle alten "required" Checks als success ----
      - name: legacy: auto-fix
        uses: peter-evans/create-or-update-commit-status@v3
        with:
          sha: ${{ steps.pr.outputs.sha }}
          context: auto-fix
          state: success
          description: Satisfied by manual legacy workflow

      - name: legacy: automerge
        uses: peter-evans/create-or-update-commit-status@v3
        with:
          sha: ${{ steps.pr.outputs.sha }}
          context: automerge
          state: success
          description: Satisfied by manual legacy workflow

      - name: legacy: create-pull-request
        uses: peter-evans/create-or-update-commit-status@v3
        with:
          sha: ${{ steps.pr.outputs.sha }}
          context: create-pull-request
          state: success
          description: Satisfied by manual legacy workflow

      - name: legacy: lint-and-validate
        uses: peter-evans/create-or-update-commit-status@v3
        with:
          sha: ${{ steps.pr.outputs.sha }}
          context: lint-and-validate
          state: success
          description: Satisfied by manual legacy workflow
