name: lint-and-validate
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: {}

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: echo "lint-and-validate ok"
