name: Merge Gate

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  gate:
    name: gate
    runs-on: ubuntu-latest
    steps:
      - name: Pass gate
        run: echo "gate ok"
