name: pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # 🟣 DEBUG: dist-Struktur anzeigen (im Log)
      - name: Show dist layout
        run: |
          echo "::group::pwd & ls"
          pwd; ls -la
          echo "::endgroup::"
          echo "::group::dist tree (max depth 2)"
          find dist -maxdepth 2 -type f -printf "%p\n" | sort
          echo "::endgroup::"
          echo "::group::dist/cards.html (head 120)"
          sed -n '1,120p' dist/cards.html || true
          echo "::endgroup::"
          echo "::group::dist/detail.html (head 120)"
          sed -n '1,120p' dist/detail.html || true
          echo "::endgroup::"

      # 🟣 DEBUG: dist zusätzlich als Download-Artefakt anhängen
      - name: Upload dist-debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-debug-${{ github.run_id }}
          path: dist
          retention-days: 1

      # offizielles Pages-Artefakt
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
