name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read      # nötig, um den Code zu lesen
  pages: write        # nötig, um auf Pages zu deployen
  id-token: write     # OIDC für actions/deploy-pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # 👉 wichtig für SPA-Routing: 404.html = index.html
      - name: SPA fallback (copy index -> 404)
        run: |
          if [ -f dist/index.html ]; then
            cp dist/index.html dist/404.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 👉 falls dein Buildordner anders heißt (z.B. build/ oder out/), hier anpassen
          path: dist

  deploy:
    name: Deploy to Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
