name: pages
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare publish artifact (flatten HTML to root)
        shell: bash
        run: |
          set -euo pipefail

          echo ">>> Repo tree (top-level and /pages)"
          (ls -la || true)
          ( [ -d pages ] && ls -la pages || true )

          rm -rf .gh-pages
          mkdir -p .gh-pages

          # 1) HTML – bevorzugt Root, Fallback aus /pages nach Root umkopieren
          for f in index.html cards.html detail.html; do
            if [ -f "$f" ]; then
              echo "Copy $f -> .gh-pages/$f"
              cp -v "$f" ".gh-pages/$f"
            elif [ -f "pages/$f" ]; then
              echo "Copy pages/$f -> .gh-pages/$f"
              cp -v "pages/$f" ".gh-pages/$f"
            else
              echo "MISS: $f (weder im Root noch unter /pages)"
            fi
          done

          # 2) Weitere HTMLs ggf. ebenfalls aus /pages (z. B. assets Seiten)
          if [ -d pages ]; then
            shopt -s nullglob
            for f in pages/*.html; do
              base="$(basename "$f")"
              if [ ! -f ".gh-pages/$base" ]; then
                echo "Copy extra HTML $f -> .gh-pages/$base"
                cp -v "$f" ".gh-pages/$base"
              fi
            done
          fi

          # 3) Daten & Skripte (Root bevorzugt, sonst unter /pages)
          for d in data scripts dist style assets; do
            if [ -d "$d" ]; then
              echo "Copy dir $d -> .gh-pages/$d"
              cp -R "$d" ".gh-pages/$d"
            elif [ -d "pages/$d" ]; then
              echo "Copy dir pages/$d -> .gh-pages/$d"
              cp -R "pages/$d" ".gh-pages/$d"
            else
              echo "MISS dir: $d"
            fi
          done

          echo ">>> Publish artifact content"
          find .gh-pages -maxdepth 2 -print

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
