name: Satisfy legacy required checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  statuses: write

jobs:
  satisfy-required-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Mark legacy required contexts as success
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const sha = context.payload.pull_request.head.sha;
            const runId = process.env.GITHUB_RUN_ID;
            const targetUrl = `https://github.com/${owner}/${repo}/actions/runs/${runId}`;

            const contexts = [
              "auto-fix",
              "create-pull-request",
              "lint-and-validate"
            ];

            for (const ctx of contexts) {
              await github.repos.createCommitStatus({
                owner,
                repo,
                sha,
                state: "success",
                context: ctx,
                description: "Satisfied by compatibility workflow",
                target_url: targetUrl
              });
            }
