name: manual-satisfy-required-checks

on:
  workflow_dispatch:
    inputs:
      pr:
        description: "PR number (e.g. 14)"
        required: true
        type: number

permissions:
  contents: read
  statuses: write
  pull-requests: read

jobs:
  set:
    runs-on: ubuntu-latest
    steps:
      - name: Set required contexts to success for given PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = Number(core.getInput('pr'));
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            const sha = pr.data.head.sha;
            const contexts = ['auto-fix','create-pull-request','lint-and-validate'];
            for (const ctx of contexts) {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha,
                state: 'success',
                context: ctx,
                description: 'set by manual-satisfy-required-checks'
              });
            }
