name: Sync dist to repo (via PR)

on:
  # Manuell startbar
  workflow_dispatch:
  # Automatisch bei relevanten Änderungen
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "public/**"
      - "cards.*"
      - "detail.*"
      - "index.html"
      - "vite.config.js"
      - "package.json"
      - "package-lock.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Optional: Artefakt anhängen, damit man den Build sofort einsehen kann
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      # Statt auf main zu pushen -> PR mit dist/**
      - name: Create PR with dist
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(dist): update built assets"
          title: "chore(dist): update built assets"
          body: "Automated build of the dist/ folder (no direct push to protected main)."
          branch: bot/update-dist
          delete-branch: true
          add-paths: |
            dist/**
