name: Task Runner v2 (Dropdown → PR + Auto-Merge)

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Payload auswählen'
        required: true
        default: 'a2'
        type: choice
        options:
          - a2
          - a3
          - a4
          - task/auto

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Copy payload
        run: |
          cp payloads/${{ github.event.inputs.payload }}.json payload.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(task): apply payload ${{ github.event.inputs.payload }}" || echo "No changes"
          git push
